(ns bobrosslipsum.quotes)

(def lines
  [;; Series 1, Episode 2
   "Sometimes the brush is lazy."
   "This is the lazy man's way of painting."
   "Use what happens naturally."
   "Don't want to set these clouds on fire."
   "You can end up with great big cotton balls in the sky if you're not careful."
   "Learn to control it."
   ;; Series 1, Episode 4
   "Make big billowy, fluffy clouds."
   "Just sorta work it around and around here."
   "We want this swirling, churning actions here."
   "Keep this brush moving all the time."
   "Now we're ready to start working it."
   "Always doing the things furthest away first and working forward."
   "Always follow the angles here."
   "It's cold, but it's beautiful."
   ;; Series 2, Episode 1
   "See how easy that was?"
   "It's very easy to make a sky darker, but it's a son of a gun to make it lighter."
   "Another thing that seems to give us a lot of problems is almighty clouds."
   "Now we'll fluff it."
   "Now, very gently, we'll hypnotize it."
   "Everybody likes mountains."
   "Always follow the angles."
   "See? I knew you could do it!"
   "Talent is a pursued interest."
   "Anything you are willing to practice, you can do!"
   ;; Series 2, Episode 2
   "I used to work for weeks to make a tree."
   "We are really trying to teach you a technique. We're not trying to teach you to copy."
   "Let your imagination be your guide."
   "Do whatever feels right."
   "There's no big secret to this."
   "Oh, the agony! I remember it."
   "I'm a nature freak."
   "You need to understand nature."
   "We spend so much of our lives looking, but never, never seeing."
   ;; Series 3, Episode 4
   "That's the most fun of all."
   "Just mix it up real good."
   "Now let's use the fan brush."
   "You just sort of have to make almighty decisions."
   ;; Series 3, Episode 10
   "Every series, we need to have a crazy day."
   "We're ready to get serious with this."
   "See how far away that looks already?"
   "We'll start playing a little bit."
   "I love to make trees."
   "Use your imagination."
   "We're gonna give him some buns to sit on."
   "Talent is nothing more than a pursued interest."
   "It should give you a lot of ideas of a lot of crazy things you can do."
   ;; Series 4, Episode 2
   "Just let it bounce around and play."
   "Let's build a happy little cloud in the sky."
   "You can do all this blending without becoming a mud-mixer."
   "It's too far away."
   "Painting used to drive me crazy."
   "It takes a very, very little bit."
   "Every time you add another plane, you create more depth."
   "Just walk right back into this painting."
   "Look at all those... thousands of leaves!"
   "You could sit there with your one-haired brush for a week trying to do that, or you can do it in one stroke with an almighty brush!"
   "Don't be afraid of it."
   "Don't worry about it; have fun with it!"
   "All you need is a dream in your heart."
   ;; Series 4, Episode 3
   "Get a nice, even distribution of paint all through the bristles."
   "Let's just sort of play a little color here and there."
   "I'm always looking for a nice, easy way to do this."
   "If you're gonna do mountains, it's fun to have little bumps on them here and there."
   "All you're doing here is whisper-light."
   "If you over-mix it, you just get one dead color."
   ;; Series 5, Episode 4
   "We never duplicate anything exactly."
   "You can always add more if you want it."
   "Brush mix!"
   "Don't let your trees get too symmetrical... too even."
   "All these little things make it interesting."
   "Find out which one works best for you, and that's the one that you want to use."
   "Angles are very, very important."
   "This is your dirt, so you put it where you want it."
   ;; Series 5, Episode 10
   "I want to do something that's just a little bit different, and I think you'll find it's fun."
   "Start with a small amount and blend upward."
   "You can begin making all kinds of beautiful shapes up in the sky."
   "Let the brush play and have fun -- let it go!"
   "Chickens need a place to live too."
   "Use a color that's a little more muted and quiet."
   "Let's have some fun today."
   "Give this ol' windmill a leg!"
   "Don't be afraid of this big brush."
   "Let us know, and we'll do some more crazy things for you."
   ;; Series 6, Episode 2
   "Ready to go!"
   "Just let it go, have fun."
   "Leave some open spots here and there."
   "Only takes a minute."
   "He lives right there -- that's his home."
   "Try not to kill it."
   "However you want to change this, that's the way it should be."
"Now we can start picking out some individual things."
"Here and there and there and here."
"Let's work on that tree right there."
"You don't want it to be flat."
;; Series 6, Episode 7
"All these fantastic things... they just sorta happen."
"You can blend this until it absolutely goes away and leaves you."
"Get it to where you want it, and leave it alone."
"Don't piddle with them -- don't worry about them."
"It's always trying to go somewhere that it can be level."
"Feel the power of the water."
"We'll make those decisions later."
;; Series 7, Episode 4
"Take right off today!"
"Let some little things just shine through."
"Leave a little area open here."
"That's why I like it so much."
"Just dance it around."
"Keep it moving."
"We're looking for happy little clouds."
"Sort of mix it up."
"Get tough with it."
"We planned this son-of-a-gun right from the beginning."
"You wouldn't buy somebody else's mistakes; nobody's going to buy yours."
"Think like a tree when you do these."
;; Series 7, Episode 8
"I want some happy little things happening up here in the sky."
"Help them make a happy buck or two."
"That knife's a little big... let me get my small knife."
"Let 'em have it!"
"Follow these angles."
"Don't want to overkill."
"That gives us a general idea of how that mountain was made."
"That son-of-a-gun is growing on us!"
"Give him some arms -- a tree needs some arms."
;; Series 8, Episode 1
"Blend color right here on the canvas."
"Don't want to set the sky on fire."
"Be sure it's odorless or you'll be working by yourself."
"You do it the way that you want it."
"Use a lot of pressure."
"All you're worried about is this nice outside shape."
"Very soft, very quiet."
"We all need a friend."
"Make friends with trees."
"Don't get carried away."
;; Series 8, Episode 8
"Let it sort of bounce around and play."
"Be... so... careful!"
"Let's build us a mountain!"
"We'll make some big ol' huge mountains!"
"Pretend you're a whisper floating across here."
"Wiggle it, then sharpen it."
"Oh dear, here comes a tree!"
"When the birds take over, I'll have friends!"
"As usual, Bob's gonna do a big tree."
;; Series 9, Episode 6
"Just leave that space open."
"Drop in some happy little shadows."
"He's a healthy cloud."
"Just sorta stir it up, don't overdo -- just enough to bring it together."
"We're just looking for a nice, basic, outside shape. We could care less what's going on inside here."
"Water breaks, and it churns, and it has fun!"
"Hit it, and get away from it."
;; Series 9, Episode 10
"We're looking for a nice, even distribution of color."
"Let's have some big, fluffy clouds in this painting."
"We'll just sort of slip in some clouds."
"You have to sort of plan these clouds."
"You do whatever works for you."
"Create that little fuzzy look."
"Don't worry about it -- just sort of throw it in."
"Big buildings are just little buildings that had a shot of vitamins."
"We don't know where that goes."
"Go out and spend some time talking to a tree."
"Trees are nice people."

])
